const IFACE = [
  { label: 'Method', keys: ['method'] },
  { label: 'Path / interface', keys: ['path_or_interface', 'path', 'interface', 'route', 'name'] },
  { label: 'Handler', keys: ['handler'] },
  { label: 'Component', keys: ['component'] },
  { label: 'Authentication', keys: ['authentication', 'auth'] },
  { label: 'Authorization', keys: ['authorization'] },
];

export const COLS = {
  components: [
    { label: 'Component', keys: ['name', 'component_id'] },
    { label: 'Type', keys: ['type'] },
    { label: 'Responsibility', keys: ['responsibility'] },
    { label: 'Dependencies', keys: ['dependencies'] },
    { label: 'Related components', keys: ['related_components'] },
  ],
  apis: IFACE,
  routes: IFACE,
  externally_accessible_interfaces: IFACE,
  data_stores: [
    { label: 'Data store', keys: ['name', 'store_id'] },
    { label: 'Type', keys: ['type'] },
    { label: 'Purpose', keys: ['purpose'] },
    { label: 'Models', keys: ['models'] },
    { label: 'Connected components', keys: ['connected_components'] },
  ],
  execution_flows: [
    { label: 'Flow', keys: ['name', 'flow_id'] },
    { label: 'Entry point', keys: ['entry_point'] },
    { label: 'Steps', keys: ['steps'] },
    { label: 'Components', keys: ['components'] },
    { label: 'Data flow', keys: ['data_flow'] },
  ],
  integrations: [
    { label: 'Service', keys: ['service', 'name'] },
    { label: 'Interfaces', keys: ['interface', 'interfaces'] },
    { label: 'Purpose', keys: ['purpose'] },
    { label: 'Direction', keys: ['direction'] },
    { label: 'Connected components', keys: ['connected_components'] },
  ],
  security_controls: [
    { label: 'Control', keys: ['control_id', 'name'] },
    { label: 'Type', keys: ['type'] },
    { label: 'Implementation', keys: ['implementation'] },
    { label: 'Protected area', keys: ['protected_area'] },
  ],
  threats: [
    { label: 'ID', keys: ['threat_id'] },
    { label: 'Scenario', keys: ['scenario'] },
    { label: 'Actor', keys: ['actor'] },
    { label: 'Entry point', keys: ['entry_point'] },
    { label: 'Components', keys: ['affected_components'] },
    { label: 'Assets', keys: ['affected_assets'] },
    { label: 'Boundaries crossed', keys: ['trust_boundaries_crossed'] },
    { label: 'Impact', keys: ['impact'] },
  ],
  threat_relationships: [
    { label: 'ID', keys: ['relationship_id'] },
    { label: 'From', keys: ['source_threat_id'] },
    { label: 'To', keys: ['target_threat_id'] },
    { label: 'Type', keys: ['relationship_type'] },
    { label: 'Why', keys: ['description'] },
  ],
  scan_focus: [
    { label: 'Scan type', keys: ['scan_type'] },
    { label: 'Target', keys: ['target'] },
    { label: 'Security context', keys: ['security_context'] },
    { label: 'Asset / business function', keys: ['asset_or_business_function'] },
    { label: 'Threat context', keys: ['threat_context'] },
    { label: 'Reason', keys: ['reason', 'reasoning', 'analysis_reasoning'] },
  ],
  threat_convergence: [
    { label: 'ID', keys: ['convergence_id'] },
    { label: 'Target type', keys: ['target_type'] },
    { label: 'Target', keys: ['target'] },
    { label: 'Converging threats', keys: ['related_threat_ids'] },
    { label: 'Reason', keys: ['reason'] },
    { label: 'Scan relevance', keys: ['scan_relevance'] },
  ],
  findings: [
    { label: 'Finding', keys: ['title', 'finding_id'] },
    { label: 'Severity', keys: ['severity'] },
    { label: 'Confidence', keys: ['confidence'] },
    { label: 'Category', keys: ['category', 'cwe'] },
    { label: 'Affected area', keys: ['affected_area', 'affected_component'] },
    { label: 'Root cause', keys: ['root_cause'] },
    { label: 'Status', keys: ['status', 'validation_state'] },
  ],
  triage_decisions: [
    { label: 'Finding', keys: ['finding_id'] },
    { label: 'Classification', keys: ['classification'] },
    { label: 'Supported', keys: ['assessment_supported', 'implementation_support'] },
    { label: 'Reachability', keys: ['reachability'] },
    { label: 'Duplicate of', keys: ['duplicate_of'] },
    { label: 'Group', keys: ['root_cause_group_id', 'consolidated_finding_id'] },
    { label: 'Reasoning', keys: ['decision_reasoning', 'correlation_reasoning'] },
  ],
  finding_relationships: [
    { label: 'From', keys: ['source_finding_id'] },
    { label: 'To', keys: ['target_finding_id'] },
    { label: 'Type', keys: ['relationship_type'] },
    { label: 'Root cause group', keys: ['root_cause_group_id'] },
    { label: 'Description', keys: ['description'] },
  ],
  priority_queue: [
    { label: 'Finding', keys: ['finding_id'] },
    { label: 'Priority', keys: ['priority'] },
    { label: 'Severity', keys: ['severity'] },
    { label: 'Exploitability', keys: ['exploitability', 'confidence'] },
    { label: 'Asset', keys: ['affected_asset'] },
    { label: 'Work plan', keys: ['work_plan', 'target_period', 'queue_position'] },
    { label: 'Reasoning', keys: ['priority_reasoning'] },
  ],
  remediations: [
    { label: 'Finding', keys: ['finding_id'] },
    { label: 'Status', keys: ['status', 'implementation_status'] },
    { label: 'Root cause', keys: ['root_cause'] },
    { label: 'Recommendation', keys: ['recommendation', 'proposed_remediation'] },
    { label: 'Changed files', keys: ['changed_files'] },
    { label: 'Validation', keys: ['security_validation', 'functional_validation'] },
    { label: 'Risk notes', keys: ['risk_notes'] },
  ],
  targeted_verifications: [
    { label: 'Finding', keys: ['finding_id'] },
    { label: 'Result', keys: ['result'] },
    { label: 'Target', keys: ['target'] },
    { label: 'Before / after', keys: ['post_remediation_condition', 'original_condition'] },
    { label: 'Root cause addressed', keys: ['root_cause_addressed'] },
    { label: 'Attack path', keys: ['attack_path_status'] },
    { label: 'Remaining issue', keys: ['remaining_vulnerable_condition', 'confidence'] },
  ],
  regression_verifications: [
    { label: 'Finding', keys: ['finding_id'] },
    { label: 'Classification', keys: ['classification', 'determination'] },
    { label: 'Regression status', keys: ['regression_status'] },
    { label: 'Components', keys: ['related_components'] },
    { label: 'Interfaces', keys: ['related_interfaces'] },
    { label: 'Linked findings', keys: ['linked_finding_ids'] },
  ],
  closure_assessments: [
    { label: 'Finding', keys: ['finding_id'] },
    { label: 'Decision', keys: ['classification'] },
    { label: 'Weakness addressed', keys: ['weakness_addressed'] },
    { label: 'Evidence sufficient', keys: ['evidence_sufficient'] },
    { label: 'Related paths checked', keys: ['related_paths_checked'] },
    { label: 'Remaining requirements', keys: ['remaining_requirements', 'closure_reasoning'] },
  ],
};

export const FIELD_LABELS = {
  purpose: 'Review summary',
  repository_scope: 'Repository scope',
  business_functionality: 'Application behavior',
  critical_business_functions: 'Critical workflows',
  entry_points: 'Entry points',
  startup_flow: 'Startup flow',
  runtime_processes: 'Runtime processes',
  scheduled_jobs: 'Scheduled jobs',
  libraries: 'Libraries',
  dependencies: 'Dependencies',
  apis: 'APIs',
  ci_cd_structure: 'CI/CD structure',
  externally_accessible_interfaces: 'Externally accessible interfaces',
  security_sensitive_apis: 'Security-sensitive APIs',
  security_sensitive_entry_points: 'Security-sensitive entry points',
  high_impact_business_operations: 'High-impact operations',
  threat_path_components: 'Components on threat paths',
  limited_visibility_areas: 'Limited visibility areas',
  unresolved_behavior: 'Unresolved behavior',
  internal_external_trust_relationships: 'Internal / external trust relationships',
  authentication_authorization_boundaries: 'Authentication & authorization boundaries',
  triage_decisions: 'Triage decisions',
  finding_relationships: 'Finding relationships',
  priority_queue: 'Priority queue',
  targeted_verifications: 'Fix verification',
  regression_verifications: 'Regression verification',
  closure_assessments: 'Closure assessments',
  analysis_reasoning: 'Reasoning',
  reasoning: 'Reasoning',
  threat_reasoning: 'Threat reasoning',
  decision_reasoning: 'Decision reasoning',
  priority_reasoning: 'Priority reasoning',
  closure_reasoning: 'Closure reasoning',
  correlation_reasoning: 'Correlation reasoning',
  remediation_reasoning: 'Remediation reasoning',
  verification_reasoning: 'Verification reasoning',
  validation_reasoning: 'Validation reasoning',
  reason: 'Reason',
  configuration_reference: 'Configuration',
  pre_scan_references: 'Earlier review references',
  previous_scan_references: 'Previous scan references',
};
